<a href="https://colab.research.google.com/github/anaglewski/data-science-bootcamp/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
x = np.array([1,3])
x 

array([1, 3])

In [4]:
print(x)
# Drukuj obiekt x

[1 3]


In [5]:
type(x)
#typ obiektu x

numpy.ndarray

In [8]:
x.ndim
# ilość wymiarów

1

In [9]:
x.shape
# Ilość elementów oraz struktura wymiarów

(2,)

In [11]:
x.size
# Liczba elementów

2

In [10]:
x.dtype
#Typ danych - nie zmiennej

dtype('int64')

In [13]:
y = np.array([1.3,2.3,1.4])
y

array([1.3, 2.3, 1.4])

In [14]:
y.dtype

dtype('float64')

In [16]:
x = np.array([[1,2],[-3,1]])
x

array([[ 1,  2],
       [-3,  1]])

In [17]:
x.ndim

2

In [18]:
x.shape

(2, 2)

In [20]:
x = np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [21]:
x.shape

(2, 3)

In [ ]:
# Tablice 3D

In [31]:
x = np.array([[[1,1,1,0],[2,2,2,0]],
              [[3,3,3,1],[4,4,4,1]]])
x

array([[[1, 1, 1, 0],
        [2, 2, 2, 0]],

       [[3, 3, 3, 1],
        [4, 4, 4, 1]]])

In [32]:
x.shape

(2, 2, 4)